### Get all games
GET http://localhost:5500/games
Accept: application/json

### Create a new game

POST http://localhost:5500/games
Content-Type: application/json

{
  "gtype": "singles",
  "gmname": "Test Game",
  "tid": "2d4aab65-7461-4c29-9e87-3040c9f59826",
  "gid": "50c6dd42-7bda-4e16-aa66-c287c13ff437"
}

### Add players to a game
POST http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc/players
Content-Type: application/json

{
  "players": [
    {
      "pid": "123baaac-2eb3-446b-8744-5dc0e57cf848",
      "gteam": "A",
      "score": 0
    },
    {
      "pid": "b98ca10a-c0b6-4537-b421-b838ec35b7ad",
      "gteam": "B",
      "score": 0
    }
  ]
}

### Get specific game by ID
GET http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc
Accept: application/json

### Get game configuration
GET http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc/config
Accept: application/json

### Update game scores
PATCH http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc/scores
Content-Type: application/json

{
  "scores": [
    {
      "pid": "123baaac-2eb3-446b-8744-5dc0e57cf848",
      "score": 10
    },
    {
      "pid": "b98ca10a-c0b6-4537-b421-b838ec35b7ad",
      "score": 5
    }
  ]
}

### Delete a game
DELETE http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc