### Get all games
GET http://localhost:5500/games
Accept: application/json

### Create a new game

POST http://localhost:5500/games
Content-Type: application/json

{
  "gtype": "singles",
  "gmname": "Test Game",
  "tid": "2d4aab65-7461-4c29-9e87-3040c9f59826",
  "gid": "50c6dd42-7bda-4e16-aa66-c287c13ff437"
}

### Add players to a game
POST http://localhost:5500/games/19a714ab-2e69-411f-b394-8fecd2599b2c/players
Content-Type: application/json

{
  "players": [
    {
      "pid": "90e69f89-e025-414d-860b-246bae753576",
      "gteam": "A",
      "score": 5
    },
    {
      "pid": "b98ca10a-c0b6-4537-b421-b838ec35b7ad",
      "gteam": "B",
      "score": 2
    }
  ]
}

### Get specific game by ID
GET http://localhost:5500/games/19a714ab-2e69-411f-b394-8fecd2599b2c
Accept: application/json

### Get game configuration
GET http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc/config
Accept: application/json

### Update game scores
PATCH http://localhost:5500/games/98a7fa50-bf7b-401e-8787-f3f4e0c553e4/scores
Content-Type: application/json

{
  "scores": [
    {
      "pid": "90e69f89-e025-414d-860b-246bae753576",
      "score": 10
    },
    {
      "pid": "b98ca10a-c0b6-4537-b421-b838ec35b7ad",
      "score": 5
    }
  ]
}

### Delete a game
DELETE http://localhost:5500/games/1f4d8bc2-05b4-44a7-8be6-935f9420dcbc